import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const {
      bookingId,
      userId,
      userName,
      userEmail,
      courseName,
      classType,
      lecturerName,
      date,
      time,
      price,
      paymentMethod,
      receiptUrl,
    } = body;

    // Create a transporter using SMTP settings from environment variables
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_SECURE === 'true', // true for 465, false for other ports
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    // Email content
    const mailOptions = {
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to: process.env.ADMIN_EMAIL || process.env.EMAIL_USER, // Send notification to admin
      subject: `New Booking: ${courseName} - ${userName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #333;">New Booking Received</h2>
          <div style="background-color: #f5f5f5; padding: 20px; border-radius: 8px;">
            <p><strong>Booking ID:</strong> ${bookingId}</p>
            <hr style="border: 1px solid #ddd;" />
            
            <h3 style="color: #555;">Student Details</h3>
            <p><strong>Name:</strong> ${userName}</p>
            <p><strong>Email:</strong> ${userEmail}</p>
            <p><strong>User ID:</strong> ${userId}</p>
            
            <h3 style="color: #555;">Booking Information</h3>
            <p><strong>Course:</strong> ${courseName}</p>
            <p><strong>Type:</strong> ${classType}</p>
            <p><strong>Lecturer:</strong> ${lecturerName}</p>
            <p><strong>Date:</strong> ${date}</p>
            <p><strong>Time:</strong> ${time}</p>
            <p><strong>Price:</strong> ${price ? `Rs. ${price}` : '-'}</p>
            
            <h3 style="color: #555;">Payment Details</h3>
            <p><strong>Method:</strong> ${paymentMethod}</p>
            ${receiptUrl ? `<p><strong>Receipt:</strong> <a href="${receiptUrl}">View Receipt</a></p>` : ''}
          </div>
          <p style="color: #888; font-size: 12px; margin-top: 20px;">
            This email was automatically generated by the SmartLabs Booking System.
          </p>
        </div>
      `,
    };

    // Verify connection configuration
    await new Promise((resolve, reject) => {
      transporter.verify(function (error, success) {
        if (error) {
          console.error('SMTP Connection Error:', error);
          reject(error);
        } else {
          console.log('Server is ready to take our messages');
          resolve(success);
        }
      });
    });

    // Send email
    await transporter.sendMail(mailOptions);

    return NextResponse.json({ message: 'Email notification sent successfully' }, { status: 200 });
  } catch (error: any) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { error: 'Failed to send email notification', details: error.message },
      { status: 500 }
    );
  }
}
